log_level: info

audio:
  sample_rate: 16000
  mic_distance: 0.15 # В метрах

vad:
  low_freq: 200
  speech_freq_start: 300
  speech_freq_end: 3000
  speech_energy_threshold: 0.1
  ratio_threshold: 1.8
  fft_size: 256

server:
  send_buf: 8192 # В байтах
  host: 127.0.0.1
  port: 8080